### ISSUE TITLE
Add --profile option

### ISSUE THREAD

**Issue by kostyrev** [ReSTARTR/ec2-ls-hosts#6]
As of now, `profile` is hard-coded in [here](https://github.com/ReSTARTR/ec2-ls-hosts/blob/master/creds/selector.go#L15).
It would be great if one could override this via config or cli.

**Comment by ReSTARTR** [comment]
I added `--profile` option.

#9 

Thanks!

**Comment by kostyrev** [comment]
You rock! thank you
